version: "3.9"

services:
  fakebox:
    image: machinebox/fakebox
    container_name: fakebox
    environment:
      - MB_KEY=${MB_KEY}
      - username=username
      - password=password
    ports:
      - 8880:8080
    restart: unless-stopped

  neo4j:
    container_name: neo4j
    image: neo4j:enterprise
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - /home/parkernisbet/neo4j/data:/data
      - /home/parkernisbet/neo4j/import:/import
      - /home/parkernisbet/neo4j/logs:/logs
      - /home/parkernisbet/neo4j/plugins:/plugins
    environment:
      - NEO4j_AUTH=neo4j/total_random_password_not_real
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*, gds.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*, gds.*
      - NEO4J_dbms_default__database=discovr

